# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 863)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(58, 61, 113);\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frm = QtWidgets.QFrame(self.centralwidget)
        self.frm.setGeometry(QtCore.QRect(10, 70, 591, 781))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frm.setFont(font)
        self.frm.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 10, 63);\n"
"    border-radius: 10px;\n"
"}")
        self.frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm.setObjectName("frm")
        self.loginlbl = QtWidgets.QLabel(self.frm)
        self.loginlbl.setGeometry(QtCore.QRect(80, 0, 431, 431))
        self.loginlbl.setText("")
        self.loginlbl.setPixmap(QtGui.QPixmap("C:/Users/MSI/Desktop/log_page.png"))
        self.loginlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.loginlbl.setObjectName("loginlbl")
        self.userline = QtWidgets.QLineEdit(self.frm)
        self.userline.setGeometry(QtCore.QRect(260, 440, 231, 41))
        self.userline.setStyleSheet("QLineEdit{\n"
"    background-color:rgb(239, 215, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.userline.setObjectName("userline")
        self.passline = QtWidgets.QLineEdit(self.frm)
        self.passline.setGeometry(QtCore.QRect(260, 490, 231, 41))
        self.passline.setStyleSheet("QLineEdit{\n"
"    background-color:rgb(239, 215, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.passline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passline.setObjectName("passline")
        self.userlbl = QtWidgets.QLabel(self.frm)
        self.userlbl.setGeometry(QtCore.QRect(80, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.userlbl.setFont(font)
        self.userlbl.setStyleSheet("color:rgb(251, 255, 0);\n"
"background-color: rgb(146, 56, 255);\n"
"border-radius: 10px;")
        self.userlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.userlbl.setObjectName("userlbl")
        self.passwordlbl = QtWidgets.QLabel(self.frm)
        self.passwordlbl.setGeometry(QtCore.QRect(80, 490, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.passwordlbl.setFont(font)
        self.passwordlbl.setStyleSheet("color:rgb(251, 255, 0);\n"
"background-color: rgb(146, 56, 255);\n"
"border-radius: 10px;")
        self.passwordlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordlbl.setObjectName("passwordlbl")
        self.loginbtn = QtWidgets.QPushButton(self.frm)
        self.loginbtn.setGeometry(QtCore.QRect(100, 610, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.loginbtn.setFont(font)
        self.loginbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginbtn.setStyleSheet("QPushButton{\n"
"    border-radius: 25px;\n"
"    background-color:rgb(56, 58, 190);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 25px;\n"
"    background-color:rgb(229, 229, 229);\n"
"    color: rgb(84, 5, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 25px;\n"
"    background-color: rgb(56, 58, 190);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.loginbtn.setObjectName("loginbtn")
        self.war = QtWidgets.QLabel(self.frm)
        self.war.setGeometry(QtCore.QRect(270, 680, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.war.setFont(font)
        self.war.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.war.setText("")
        self.war.setAlignment(QtCore.Qt.AlignCenter)
        self.war.setObjectName("war")
        self.bucket = QtWidgets.QPushButton(self.frm)
        self.bucket.setGeometry(QtCore.QRect(490, 604, 41, 41))
        self.bucket.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bucket.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color:  white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color:rgb(166, 166, 166);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.bucket.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/MSI/Desktop/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bucket.setIcon(icon)
        self.bucket.setIconSize(QtCore.QSize(35, 33))
        self.bucket.setObjectName("bucket")
        self.randcode = QtWidgets.QLabel(self.frm)
        self.randcode.setGeometry(QtCore.QRect(270, 590, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.randcode.setFont(font)
        self.randcode.setStyleSheet("QLabel{\n"
"    color: rgb(255, 239, 14);\n"
"    background-color: rgb(74, 74, 74);\n"
"}")
        self.randcode.setText("")
        self.randcode.setAlignment(QtCore.Qt.AlignCenter)
        self.randcode.setObjectName("randcode")
        self.randline = QtWidgets.QLineEdit(self.frm)
        self.randline.setGeometry(QtCore.QRect(260, 540, 231, 41))
        self.randline.setStyleSheet("QLineEdit{\n"
"    background-color:rgb(239, 215, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.randline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.randline.setObjectName("randline")
        self.passwordlbl_2 = QtWidgets.QLabel(self.frm)
        self.passwordlbl_2.setGeometry(QtCore.QRect(80, 540, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.passwordlbl_2.setFont(font)
        self.passwordlbl_2.setStyleSheet("color:rgb(251, 255, 0);\n"
"background-color: rgb(146, 56, 255);\n"
"border-radius: 10px;")
        self.passwordlbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordlbl_2.setObjectName("passwordlbl_2")
        self.login = QtWidgets.QLabel(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(220, 10, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login.setFont(font)
        self.login.setStyleSheet("QLabel{\n"
"    color:rgb(251, 255, 0);\n"
"    background-color: rgb(146, 56, 255);\n"
"    border-radius: 25px;\n"
"}")
        self.login.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.login.setObjectName("login")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(570, 10, 31, 31))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color:rgb(166, 166, 166);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.exit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/MSI/Desktop/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon1)
        self.exit.setIconSize(QtCore.QSize(25, 26))
        self.exit.setObjectName("exit")
        self.restore = QtWidgets.QPushButton(self.centralwidget)
        self.restore.setGeometry(QtCore.QRect(530, 10, 31, 31))
        self.restore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restore.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color:rgb(166, 166, 166);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.restore.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/MSI/Desktop/restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore.setIcon(icon2)
        self.restore.setIconSize(QtCore.QSize(24, 24))
        self.restore.setObjectName("restore")
        self.minsize = QtWidgets.QPushButton(self.centralwidget)
        self.minsize.setGeometry(QtCore.QRect(490, 10, 31, 31))
        self.minsize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minsize.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color:rgb(166, 166, 166);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.minsize.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/MSI/Desktop/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minsize.setIcon(icon3)
        self.minsize.setIconSize(QtCore.QSize(28, 28))
        self.minsize.setObjectName("minsize")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.exit.clicked.connect(MainWindow.close) # type: ignore
        self.restore.clicked.connect(MainWindow.showMaximized) # type: ignore
        self.minsize.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userlbl.setText(_translate("MainWindow", "User Name"))
        self.passwordlbl.setText(_translate("MainWindow", "Password"))
        self.loginbtn.setText(_translate("MainWindow", "Login"))
        self.passwordlbl_2.setText(_translate("MainWindow", "Random Password"))
        self.login.setText(_translate("MainWindow", "Login"))